
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/Sidebar";
import ClientLayoutWrapper from "../components/ClientLayoutWrapper";
import ClientLastVisitWrapper from "../components/ClientLastVisitWrapper";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cookies } from "next/headers";
import { AuthProvider } from "../providers/AuthProvider";
// import axios from "axios";
// import { redirect } from "next/navigation";
import LoginForm from "../features/auth/LoginForm";

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  // const router = useRouter();
  console.log(token);
  let user = null;
  let isAuthorized = false;



  if (token) {
    try {
      const res = await fetch("http://localhost:3030/api/v1/auth/user/me", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
        credentials: "include",
        cache: "no-store",
      });
      if (res.ok) {
        const data = await res.json();
        user = data.user;
        isAuthorized = true;
      }
    } catch (e) {
      console.log(e);
    }
  }



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {isAuthorized && <Sidebar />} */}

        <AuthProvider initialUser={user} initialAuth={isAuthorized}>
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}

